### ISSUE TITLE
Evaluating the speed-up graphs

### ISSUE THREAD

**Issue by majpoynton** [HPCE/hpce-2017-cw1#15]
The spec says

> For each of the implementations you will produce a graph

which must

> Compare all four implementations in some meaningful way

and then goes on to say 

> Task: Evaluate the scaling against max-iter (x-axis) with the baseline width, height, max-frames, and save it as results/scaling_max_iter.pdf.
> Task: Evaluate the scaling against dimension (x-axis), where dimension (N) is defined the same way as the earlier experiment (image size is NxN) and save it as results/scaling_dimension.pdf.
> Task: Evaluate the scaling with width, and save as results/scaling_width.pdf.
> Task: Evaluate the scaling with height, and save as results/scaling_height.pdf.
> Task: Evaluate the scaling with max-frames, and save as results/scaling_max_frames.pdf.

I might be a little confused here, but if each graph compares all four implementations wouldn't that make 3 of the graphs redundant?

So are we supposed to make 4 graphs (one for each implementation), then another 5 graphs (scaling_max_iter.pdf etc.) where the 5 scaling experiments are only done on parallel_both, to make 9 in total, or are we supposed to make 20 graphs, i.e. do the experiments scaling each of the 5 parameters for each of the 4 implementations? Or what are we supposed to do?
Sorry if I've misunderstood.

Thanks

**Comment by quarterdeveloper** [comment]
Yoooo Max. I don't even understand what we're supposed to doooo LOLOL.

I know the plotting graphs bit but i'm still stuck with plotting graphs

**Comment by narobertson42** [comment]
![example](https://cloud.githubusercontent.com/assets/9286660/19412184/10cd0436-9308-11e6-8c9a-840b8991718b.png)

I believe you need to generate a graph like this which compares all four implementations for each input parameter that can be scaled

**Comment by jeremych1000** [comment]
I've got 20 graphs, so 5 (scalable parameters) X 4 (implementations). Scaling is similar to @nar213 .

**Comment by majpoynton** [comment]
I did think 5 graphs, each comparing all 4 implementations on the parameter being scaled made the most sense, especially since the 4 graphs aren't tasks, whereas the 5 are.
Thanks both

**Comment by jeremych1000** [comment]
@majpoynton Sorry I was confusing. I had 20 graphs from all the different permutations of engine/parameter changes, but then plotted 5 graphs with each graph having 4 data sets. So I ended up with 5 graphs (ref @nar213 's comment) too.

**Comment by m8pple** [comment]
@nar213 and @jeremych1000 have the right idea.

Part of what I'm trying to get people used to is the idea of performance
as being relative, which means it has to be relative to something. As you
incrementally change a program the performance will change in different
ways for different parameters, so you need to be able to look at them
side-by-side on a single graph.

This is motivated by experiences where people will produce independent
graphs for different implementations, with different y axis scales. The
data is there, but not in an actionable format (what can I learn from it?)

A comment on @nar213 's graph - it shows the right data, and is exactly
the kind of comparison I'm looking for, but some possible tweaks:
- You are varying an independent parameter, so in principle it is a curve. Connecting
  the points with a line makes sense in that context (though with straight
  lines rather than curves (curve interpolation is usually bad). However, keep
  the points as well, so we can see where the sample points are.
- The key thing we are investigating is how this is scaling with a parallel implementation
  on multiple cores, and looking at how it scales compared to a sequential implementation.
  So a key piece of information (e.g. in the title) becomes...
- Don't forget labels on the x and y axis. Is time in seconds or minutes? What is the parameter

(I realise you might have cut those out before putting the graph up here).
