### ISSUE TITLE
How to Plot Graphs: VMWare CentOS on Mac OSX

### ISSUE THREAD

**Issue by quarterdeveloper** [HPCE/hpce-2017-cw1#16]
Good Evening Ladies and Gents,

As a new comer to command line and basically to programming. I'm trying to explore how to plot graphs using the data retrieved from max-iter and -width -height.

The data are output and saved to a txt file, while on almost all the GNUPLOT tutorials they're using plot 'XXX.dat', so I simply changed the >>abc.txt to >>abc.dat which successfully gave me max-iter.dat and dimension-vs-time.dat apparently. The output format on txt file looks like something in the following:

MAX_ITER: 1

real    0m0.015s
user    0m0.004s
sys 0m0.003s

MAX_ITER: 10

real    0m0.014s
user    0m0.004s
sys 0m0.001s

After I installed GNUPLOT and ran gnuploy -> set term jpeg (not sure which type to set to), I did

plot 'max_iter_time.dat' 

but got the return msg: bad data on line 1 of of file max_iter_time.dat

I believe this error message comes from the format of my file. Would anyone be able to give me some ideas on how to solve the problem? 

Many thanks and lots of love,
Shawn

**Comment by jeremych1000** [comment]
You need to extract the useful info from your .dat file. I'd suggest outputting to a .csv with <max_iter>, <time> on each line so gnuplot can read it. Otherwise gnuplot has no idea how to extract the max iteration values and time values from your data file.

**Comment by m8pple** [comment]
You might be trying to jump ahead into lower-level tools
sooner than is needed. It is also possible to use open office
from within VMWare, which provides an excel-like interface
with a GUI.

Remember that you can also do the development/timing on
one platform, then the plotting/data-processing on another
platform. In this instance, you could share a folder between
the OS X host and the CentOS guest, and use whatever plotting
tools you would normally use in OS X. See:
https://www.vmware.com/support/ws5/doc/ws_running_sharedfolder_adding.html
or other documents on "shared folders" for VMWare.

Splitting the dev/eval and output/visualisation is a good idea,
rather than cheating in some way or not doing the right thing.
Often the output side isn't installed on the dev machine for good
reason.

Beyond that, I'd agree with the comment about csv files. Turning
data into csv is one of the post portable formats.

**Comment by quarterdeveloper** [comment]
Hi Jeremy,

Thanks for pointing it out.

Dr. Thomas, 

Was trying to get ahead of myself too much. Thanks for the detailed reply!

**Comment by m8pple** [comment]
It's worth keeping knowledge of the existence of things like `gnuplot` in your
mental back-pocket for future use, as eventually you may want to start
_automatically_ generating graphs. For example, it is useful to set up scripts
which will set up the environment, run the tests, and then plot the graphs,
all from one script. That's when the GUI tools become unwieldy,
and a scripted approach becomes invaluable.

Automated performance testing is very common, and they track both
performance improvement and degradation. See for example the [Perf tracking for chrome](https://chromeperf.appspot.com), though that is a very sophisticated example.

This trade-off between "time-spent-automating" versus
"number-of-times-automated-thing-is-done" is a difficult balance to
strike. The more you know about automating things, the lower the
effort required to automate, 

As an aside, it is worth noting that [`matplotlib`](http://matplotlib.org/) is
gaining ground as the default method for scripted graph generation:
- Quality of output as good as matlab (or gnuplot)
- Scriptable from python
- Runs in-process, rather than as a seperate process (tends to mean it is faster)
