### ISSUE TITLE
To increase precision of time in shell

### ISSUE THREAD

**Issue by lynx5120** [HPCE/hpce-2017-cw1#20]
I'm trying to output `time` response to `1.dat` using the following script in shell:

`time -f "%E" -a -o 1.dat  bin/julia -engine $j -max-iter 512 -max-frames 1  > /dev/null` 

But I only get 2 digits after the decimal point like `0.04s`.

If I use  `TIMEFORMAT='%3R'` before the upper `time` script, then I'll get:

`0.00user 0.00system 0:00.01elapsed 9%CPU (0avgtext+0avgdata 1452maxresident)k
0inputs+0outputs (0major+426minor)pagefaults 0swaps`

How could I get 3 digits?

**Comment by m8pple** [comment]
The `time` command is sadly a bit non-standard once it goes beyond basic usage.
There is also the problem that using `time` has an intrinsically limited accuracy
due to all the system overhead, so reporting with high precision is also often
reporting system noise. For more accurate timing of short events you need
to move inside the process, which is why I use internal timers for CW2.

Another problem is that there is a `bash` builtin command called `time`, but also
an actual programme called `/usr/bin/time`. For example, on my system I get:

```
dt10@TOTO /cygdrive/e/_dt10_/documents/teaching/2016/hpce/scripts
$ TIMEFORMAT='%3R'
$ time sleep 1
1.054

dt10@TOTO /cygdrive/e/_dt10_/documents/teaching/2016/hpce/scripts
$ /usr/bin/time sleep 1
0.00user 0.01system 0:01.03elapsed 1%CPU (0avgtext+0avgdata 406272maxresident)k
0inputs+0outputs (1637major+0minor)pagefaults 0swaps
```

Using the bash builtin will get you 3 digits, but no more.

If you really want to go further, you could measure start and
stop points. For example this gives you wall-clock time:

```
$ date "+%s.%N"
1476786066.858656200
```

So you could do:

```
dt10@TOTO /cygdrive/e/_dt10_/documents/teaching/2016/hpce/scripts
$ START=$(date "+%s.%N"); sleep 1; FINISH=$(date "+%s.%N");

dt10@TOTO /cygdrive/e/_dt10_/documents/teaching/2016/hpce/scripts
$ echo "$START, $FINISH"
1476786146.195194000, 1476786147.231253300
```

But there is probably even more overhead involved starting up the
various processes. So this would give you more _precision_, but probably
less _accuracy_.

**Comment by lynx5120** [comment]
Maybe I made a little confusion here. Actually I have a file like `test.sh` and then run `lynx@XXX ~/hpce-2016-cw1$ sh test.sh` to automatically write outputs (really don't want to manually deal  with loads of numbers......) to files. The script I mentioned above is actually in `test.sh`. And I guess `time` in there would actually run `/usr/bin/time`.

I've worked a lot on time command and just cannot get satisfying outputs. I would try another ways...
However I just would like to know, could I just submit that with 2 digits if it is able to give a decent result?

**Comment by jeremych1000** [comment]
If your test set has large enough numbers the third digit shouldn't matter... What's the range of your test set?

**Comment by lynx5120** [comment]
@jeremych1000 For the task of scaling_dimension, I use 1~5000 for both width and height. And real time results for parallel engine are over 3 s.

**Comment by m8pple** [comment]
As @jeremych1000 points out, if the numbers you're measuring are large, the impact of
more decimal places is limited. If you're measuring something that takes 0.1 seconds,
you'll be getting within ~10% of time.

It becomes very difficult to measure small periods of time with any accuracy when
the OS is involved, as it becomes unclear what exactly is being measured. Is a 2ms
delay due to a disk seek, or something else? If there is a standard-deviation of
10ms, what does that mean?

Plus remember that I have literally no way of knowing what the execution time is for
your particular platform - even if I were interested, I couldn't actually check anything
down to the 3rd decimal digit. The main point is to look at the trends, and the
general trend is that for very small execution times you'll probably see a lot of
noise/variation in the measurements.

**Comment by lynx5120** [comment]
That is reasonable. You both are totally right for the precision things.

Thanks a lot.
