### ISSUE TITLE
Mac OS - Tests 11 and 14 always failing in test_submission.sh

### ISSUE THREAD

**Issue by Pietromarone** [HPCE/hpce-2017-cw1#27]
Hi everyone,

I tried to run the testing script and tests 11 and 14 kept failing, but when I tried to compare the performances manually the different optimisations were working as expected.

After a bit of debugging I realised the problem was the "date" command in the testing script, which doesn't seem to allow the use of %N to return nanoseconds on OSX (see http://stackoverflow.com/questions/9804966/date-command-does-not-follow-linux-specifications-mac-os-x-lion). This caused all performance comparisons in the script to be invalid.

The way I solved the issue was by installing coreutils ('brew install coreutils') and then changing the 2 occurrences of "date" to "gdate" in the testing script.

Suggest changing the testing script to account for this.

**Comment by m8pple** [comment]
Ah, ok thanks, plus thanks for the solution as well.

I'll update the script, though not till later as I don't want to upload without trying
to test (I don't have a mac at the moment, will have to think a bit carefully).

**Comment by majpoynton** [comment]
Mine also fails tests 11 and 14 but I am using a Linux VM on Windows.
What does it mean that those tests are wrong?
Also,

> FAIL, For wide output reference time 8930 slower than parallel_inner 7733 (0)

I'm confused - isn't the above what we expect? If a "wide" output is iteration over a large x range, then wouldn't parallel_inner be faster than the reference because the inner loop (the one we parallelised in parallel_inner) is the one iterating over x?

Edit - Solved it, sorry. 8930 is slower than 7733 and this is expected but it's not slower enough for the test to pass
Also was running on a VirtualBox instance that had only 1 CPU allocated (silly) hence why it was so similar.
Thanks

**Comment by pierrezaza** [comment]
@Pietromarone easier fix that doesn't require changing the test script:

The brew install gives a message at the end: 

```
All commands have been installed with the prefix 'g'.

If you really need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:

    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

Additionally, you can access their man pages with normal names if you add
the "gnuman" directory to your MANPATH from your bashrc as well:

    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
```

I just ran `PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"` and now all tests pass! :)

**Comment by m8pple** [comment]
Going to shut this now for a sense of closure. Thanks to @Pietromarone and @pierreazalbert.
