### ISSUE TITLE
Segmentation Fault when running -engine parallel_inner

### ISSUE THREAD

**Issue by bngzl** [HPCE/hpce-2017-cw1#42]
Hi, 

When I run time bin/julia -engine parallel_inner >/dev/null, the terminal gives me a prompt of 'Segmentation Fault' after the real,user and sys time. 

This phenomenon occurs unpredictably, i.e after running the code 50 times, there will be about 5 random instances of segmentation faults. I have tried to troubleshoot the issue by 1) running the original engine reference code and the segmentation faults disappear. 2) Reverting back the parallel code to the sequential for loops in parallel_inner also makes the segmentation fault indication go away. These seem to point that perhaps my tbb::parallel_for implementation is the problem. However, my friend has tried running my parallelisation code on his terminal and no segmentation fault occurs.

I am using MINGW64 on MSYS2 and have also tried make clean and re-compiling the make files several times. This segmentation fault does not seem to affect the relative timings in that the parallelised code is faster than the sequential optimised -o3 code nonetheless.  

Why does this 'segmentation fault' occur?

Thanks!

**Comment by malharjajoo** [comment]
I believe I have seen a peer with a similar issue, his C++ file was incorrectly modified. Check if your 
for-loops have the "width" and "height" variable in the correct place ?

**Comment by bngzl** [comment]
@malharjajoo thanks for your suggestion but I don't think that's the issue because my friend ran my code and it works fine on his terminal.. I tried rechecking my code though and I don't see anything wrong with it! I also tried his code on my terminal (which worked on his terminal) and it still provided the same erratic segmentation fault.

**Comment by m8pple** [comment]
I've never seen similar behaviour under mingw+TBB - has anyone else seen it?

It sounds like a problem with either your environment (i.e. your base operating
system or mingw), or your hardware, particularly if the same code ran correctly
on another machine, and is non-deterministically failing on your machine.
It's not clear if you mean the same C code, but compiled and run on a different
machine, or the same binary run on a different machine. I'm guessing the former.

Does the same problem also happen with parallel_outer, or is it only parallel_inner?
I ask because it sounds as if the problem is something todo with task-creation
or multi-thread communication, and parallel_inner creates many short-lived
tasks, but parallel_outer creates far fewer.

Also, when the crash happens, is the output correct? i.e. if you send it to a file
````
bin/julia -engine parallel_inner > crashy.txt
````
is the output still correct when it crashes?

In terms of debugging, you have a few options, none of which are guaranteed
to help diagnose it exactly:
- Run it in a debugger, e.g. `gdb`. Hopefully it will catch the segmentation fault
   happening, and at least tell you where the problem is. This is a little complex
   if you don't have experience of using gdb - if you want detailed instructions,
   then I can put basic steps up here.
- Do some printf debugging. If you add calls to `fprintf(stderr, "Wibble\n");`, you
  can track when your program passes through particular points (stderr is unbuffered,
   so is printed immediately). If the problem happens after `main` exits, then it
   is probably something todo with either TBB or the C standard library unwinding.
   But again, this could be caused by either software corruption, or hardware problems.
- Run a multi-threaded CPU stress test. If you can put your CPU under heavy load
   for a while, you may see errors occur, which would mean there is a problem with
   the hardware. e.g. 
- Try nuking your mingw install, and re-creating from scratch. There is a chance that
   some of the binaries have got corrupted (though it is a bit of an outside chance).

If that doesn't isolate the problem, you could just use a college computer. You
can still do development on your own machine, but it would be a little
worrying to do performance testing.

**Comment by bngzl** [comment]
The problem happens for all parallel_inner, parallel_outer and parallel_both. I tried checking the output text file when 'segmentation fault' occurs and the output seems fine. 

The overall trends I get seem to make sense so far though, however I've noticed that I have to keep doing 'make bin/julia -B' before experimenting on each engine to make sure the optimisation works (i.e only the experiment just after make bin/julia will see (i.e 0.3s) but subsequent runs of the exact same engine will see a consistent increase in time even at the same parameters (i.e 0.6s)) Could this be another symptom of the same fault? 

Does this problem really affect the overall coursework in general? I would find using a college computer to be a bit inconvenient. :/ 

Thank you!

**Comment by m8pple** [comment]
Hrmm, I'm not sure quite what is going on there. I would hesitate to rely
on a system I didn't fully trust, as you're at risk of making incorrect
decisions due to faulty data.

For the rest of the courseworks you can switch over to an AWS instances, and
use them remotely (as it is the only way they can be used). Just make sure
to do any development/debugging in a _cheap_ instance, then switch to
an expensive one only for performance testing. For example, a 4-core `c4.xlarge`
[on-demand instance](https://aws.amazon.com/ec2/pricing/on-demand/) is only $0.2 an hour, so if you're working on it for 5 hours it is only
a dollar. If you do [spot pricing](https://aws.amazon.com/ec2/spot/pricing/) it is currently
only $0.05 an hour, but you should bid more than that to stay above the spot
price (e.g. $0.1 an hour is probably safe), otherwise your instance might get terminated.

**Comment by bngzl** [comment]
I think I've found the solution! I realised as I re-cloned the git folders further out in my directory, the number of segmentation faults decreased... 

Hence, I simply just re-cloned the repo into the highest directory possible in C:\ and the problem was resolved! I guess it could be a referencing to too deep a file directory.. does this make sense? @m8pple 

Thank you for your help!

**Comment by m8pple** [comment]
`¯\_(ツ)_/¯`

No idea why that would cause non-determinstic seg-faults, but at least it's fixed. It's possible
it was creating some kind of temporary file, or... nope, no idea.
