### ISSUE TITLE
Using more than 5 parameters for x-axis ?

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw1#52]
Hi

This might sound strange, but is there a possible penalty if we choose more than 5 values ( say, around 30 values ) on the x-axis for the graphs in the last 4 pdf deliverables ?

**Comment by m8pple** [comment]
Nope, in general more points is much better as long as they don't obscure the message.

Some people might just do an automated run through, and get quite a dense coverage,
while others might manually add points in to explore interesting parts of the graph.
Either method is fine, as long as you try to cover both ends of the dependent range.
You're interested in asymptotic behaviour for small and large values, plus any
interesting variations in the transition zone (if there is one).

There is no idea of penalties for the graphs - they are fine as long as they show
a good faith effort to produce and present the requested data. They are only
required in order to guide you towards some ways of thinking about measuring
performance, and what kinds of behaviour you might see and need to explain.
