### ISSUE TITLE
Issues when running test_submission.sh

### ISSUE THREAD

**Issue by m0zjo-code** [HPCE/hpce-2017-cw1#53]
Hi all,

I am attempting to test my work but the test script seems to be hanging after test 1 completes. It could be that it just takes a really long time to complete but I am seeing no CPU activity. Is anyone else having this issue? 
Thanks! 

Screen grab below:

![screenshot at 2017-10-17 15 33 24](https://user-images.githubusercontent.com/11596712/31671055-f1556458-b350-11e7-86b4-139bf5c1866c.png)

**Comment by guigzzz** [comment]
Test 2 simply executes the code using the `parallel_inner` engine. Does this work when you execute it manually?

**Comment by m0zjo-code** [comment]
Yeah - it works when I run it normally although I found that I always had
to use the -non-progressive flag otherwise it hangs during execution.

On 17 Oct 2017 16:08, "Guillaume Ramé" <notifications@github.com> wrote:

Test 2 simply executes the code using the parallel_inner engine. Does this
work when you execute it manually?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HPCE/hpce-2017-cw1/issues/53#issuecomment-337260707>,
or mute the thread

**Comment by m8pple** [comment]
This kind of behaviour can sometimes be due to not all the pixels being calculated.

You might want to look quite carefully at definition of the `parallel_for` iteration
space. If you have:
```
for(unsigned i=0; i<width; i++){
  f(i);
}
```
then it is over the half-open iteration space of `[0,width)`.

You might want to double-check how you are defining the iteration space
for `parallel_for` and check that they match. Are you always calculating
the last row or the last column?

**Comment by m0zjo-code** [comment]
Yes that was the problem - all fixed now, thank you very much @m8pple and @guigzzz
