### ISSUE TITLE
Unclear task requirements for optimisation

### ISSUE THREAD

**Issue by JiyuFang-git** [HPCE/hpce-2017-cw1#66]
For tasks under section <Turning on opmisations>, It is not clear what graph we are asked to plot:

![image](https://user-images.githubusercontent.com/24462863/51277927-f670f280-19d0-11e9-8462-f199713461d7.png)

The graph title doesn't match the description given. For example, for the second task, are we asked to plot speedup (debug time - release time) versus debug time or scale versus speedup?

Thanks

**Comment by jjd06** [comment]
Yes, that's an unfortunate use of the word "versus" for the first graph -- apologies. For that one, you should have two lines, both showing scaling factor (x) against time (y), for the debug and release builds. The second should use the same data to produce one line (showing speedup). Remember that speedup is relative: debug_time/release_time, not debug_time - release_time.

Note that this issue was opened in a personal repo. There's no guarantee that I'll even see future personal repo issues, so please be sure to open them in the relevant master coursework repos.

**Comment by JiyuFang-git** [comment]
> Yes, that's an unfortunate use of the word "versus" for the first graph -- apologies. For that one, you should have two lines, both showing scaling factor (x) against time (y), for the debug and release builds. The second should use the same data to produce one line (showing speedup). Remember that speedup is relative: debug_time/release_time, not debug_time - release_time.
> 
> Note that this issue was opened in a personal repo. There's no guarantee that I'll even see future personal repo issues, so please be sure to open them in the relevant master coursework repos.


Thanks for your reply.

Just want to make it clear about the graphs to save in /results. Is it true that:
First task: a graph of max_iter versus time of both debug and release(log-log)
Second task: a graph of dimension versus speed-up(debug/release)(log-linear)

Thank you.

**Comment by jjd06** [comment]
The data to plot is correct. I leave it up to you to decide whether linear or log scales are appropriate for particular axes, but what you've suggested sounds sensible to me.
